export const languages = Array.from(
	new Map(
		[
			{ code: 'en', name: 'English (English)' },
			{ code: 'bn', name: 'Bangla (বাংলা)' },
			{ code: 'hi', name: 'Hindi (हिन्दी)' },
			{ code: 'es', name: 'Spanish (Español)' },
			{ code: 'ar', name: 'Arabic (العربية)' },
			{ code: 'fr', name: 'French (Français)' },
			{ code: 'zh-CN', name: 'Chinese (中文)' },
			{ code: 'ru', name: 'Russian (Русский)' },
			{ code: 'pt', name: 'Portuguese (Português)' },
			{ code: 'ur', name: 'Urdu (اردو)' },
			{ code: 'de', name: 'German (Deutsch)' },
			{ code: 'ja', name: 'Japanese (日本語)' },
			{ code: 'it', name: 'Italian (Italiano)' },
			{ code: 'ko', name: 'Korean (한국어)' },
			{ code: 'pl', name: 'Polish (Polski)' },
			{ code: 'tr', name: 'Turkish (Türkçe)' },
			{ code: 'nl', name: 'Dutch (Nederlands)' },
			{ code: 'th', name: 'Thai (ไทย)' },
			{ code: 'sv', name: 'Swedish (Svenska)' },
			{ code: 'fi', name: 'Finnish (Suomi)' },
			{ code: 'he', name: 'Hebrew (עברית)' },
			{ code: 'cs', name: 'Czech (Čeština)' },
			{ code: 'da', name: 'Danish (Dansk)' },
			{ code: 'no', name: 'Norwegian (Norsk)' },
			{ code: 'ro', name: 'Romanian (Română)' },
			{ code: 'sk', name: 'Slovak (Slovenčina)' },
			{ code: 'hu', name: 'Hungarian (Magyar)' },
			{ code: 'uk', name: 'Ukrainian (Українська)' },
			{ code: 'id', name: 'Indonesian (Bahasa Indonesia)' },
			{ code: 'ms', name: 'Malay (Bahasa Melayu)' },
			{ code: 'vi', name: 'Vietnamese (Tiếng Việt)' },
			{ code: 'sr', name: 'Serbian (Српски)' },
			{ code: 'bs', name: 'Bosnian (Bosanski)' },
			{ code: 'mk', name: 'Macedonian (Македонски)' },
			{ code: 'sq', name: 'Albanian (Shqip)' },
			{ code: 'cy', name: 'Welsh (Cymraeg)' },
			{ code: 'la', name: 'Latin (Latina)' },
			{ code: 'sw', name: 'Swahili (Kiswahili)' },
			{ code: 'tl', name: 'Tagalog (Filipino)' },
			{ code: 'am', name: 'Amharic (አማርኛ)' },
			{ code: 'ne', name: 'Nepali (नेपाली)' },
			{ code: 'km', name: 'Khmer (ខ្មែរ)' },
			{ code: 'my', name: 'Burmese (မြန်မာ)' },
			{ code: 'lo', name: 'Lao (ລາວ)' },
			{ code: 'si', name: 'Sinhala (සිංහල)' },
			{ code: 'ha', name: 'Hausa (هَوُسَ)' },
			{ code: 'jw', name: 'Javanese (ꦧꦱꦗꦮ)' },
			{ code: 'eu', name: 'Basque (Euskara)' },
			{ code: 'gl', name: 'Galician (Galego)' },
			{ code: 'oc', name: 'Occitan (Occitan)' },
			{ code: 'te', name: 'Telugu (తెలుగు)' },
			{ code: 'ta', name: 'Tamil (தமிழ்)' },
			{ code: 'ml', name: 'Malayalam (മലയാളം)' },
			{ code: 'mr', name: 'Marathi (मराठी)' },
			{ code: 'kn', name: 'Kannada (ಕನ್ನಡ)' },
			{ code: 'pa', name: 'Punjabi (ਪੰਜਾਬੀ)' },
			{ code: 'gu', name: 'Gujarati (ગુજરાતી)' },
			{ code: 'or', name: 'Odia (ଓଡ଼ିଆ)' },
			{ code: 'ba', name: 'Bashkir (Башҡортса)' },
			{ code: 'hy', name: 'Armenian (Հայերեն)' },
			{ code: 'is', name: 'Icelandic (Íslenska)' },
			{ code: 'lv', name: 'Latvian (Latviešu)' },
			{ code: 'et', name: 'Estonian (Eesti)' },
			{ code: 'lt', name: 'Lithuanian (Lietuvių)' },
		].map((lang) => [lang.code, lang])
	).values()
);
